CREATE TABLE IF NOT EXISTS home_content (
  homeContentId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(125) NOT NULL,
  content TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);